image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    
before_script:
  - npm install "@emotion/react@11.10.6" "@emotion/styled@11.10.6" "@material-ui/core@4.12.4  --force" "@material-ui/icons@4.11.3" "@mui/icons-material@5.11.0" "@mui/material@5.11.13" "@testing-library/jest-dom@5.16.5" "@testing-library/react@13.4.0" "@testing-library/user-event@13.5.0" "react-dom@18.2.0" "react-router-dom@6.8.0" "react-scripts@5.0.1" "web-vitals@2.1.4"

build:
  stage: build
  script:
    - cd my-app
    - npm install
    - npm run build

# test:
#   stage: test
#   script:
#     - npm install
#     - npm run test

# deploy:
#   stage: deploy
#   script:
#     - npm install
#     - npm run deploy
