# .gitlab-ci.yml

# Define the stages of the pipeline
stages:
  - build
  - test
  - deploy
`
# Define the jobs and their steps
build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - npm ci
    - npm run test

production_deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here for production environment

staging_deploy:
  stage: deploy
  script:
    - echo "Deploying to staging..."
    # Add your deployment commands here for staging environment
