image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - cd my-app
    - npm install
    - npm install @material-ui/core --force
    - npm run build

# test:
#   stage: test
#   script:
#     - npm install
#     - npm run test

# deploy:
#   stage: deploy
#   script:
#     - npm install
#     - npm run deploy
